spring.application.name=tenpo

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/tenpo
spring.r2dbc.username=tenpo
spring.r2dbc.password=tenpo
spring.sql.init.mode=always

spring.data.redis.host=localhost
spring.data.redis.port=6379

percentage.value=10.0
percentage.failure-probability=0.0
percentage.cache-ttl-minutes=30

ratelimit.max-requests=3
ratelimit.window-seconds=60
